public class UIEvents
{
    public const string UPDATE_BUILDING_COUNTER = "UPDATE_BUILDING_COUNTER";
    public const string UPDATE_BUILDING_PROGRESS_BAR = "UPDATE_BUILDING_PROGRESS_BAR";
    public const string TOGGLE_BUILDING_PROGRESS_BAR = "TOGGLE_BUILDING_PROGRESS_BAR";
    public const string TOGGLE_BUILD_BUTTON = "TOGGLE_BUILD_BUTTON";
    public const string CHANGE_DESTROY_BUTTON_POSITION = "CHANGE_DESTROY_BUTTON_POSITION";
    public const string TOGGLE_BUILDING_MODE_UI = "TOGGLE_BUILDING_MODE_UI";
    public const string TOGGLE_DESTROY_MODE_UI = "TOGGLE_DESTROY_MODE_UI";
    public const string TOGGLE_TILEMAP_GENERATION_SCREEN = "TOGGLE_TILEMAP_GENERATION_SCREEN";
}
